digitalclubb/remindwise.io

- apps/app/package.json
- apps/app/src/routes/(auth)/auth/callback/+server.ts
- apps/app/src/routes/(auth)/register/+page.server.ts
- pnpm-lock.yaml
After a user registers and they confirm the sign up by clicking the link in the email it wasn't redirecting them to the dashboard. This PR addresses that, there was a change on how to do auth with supabase and sveltekit that we needed to implement.
Resolves: #xxx
> fix: register redirect email

- apps/app/package.json
- apps/marketing/package.json
- package.json
- pnpm-lock.yaml
Pinning dependencies to allow for managed updates via dependabot.
> chore: pinning dependencies

- .github/workflows/testing.yml
- .gitignore
- apps/app/package.json
- apps/marketing/package.json
- apps/marketing/playwright.config.ts
- apps/marketing/tests/homepage.spec.ts
- apps/marketing/tests/pom/homepage.ts
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- turbo.json
Adding playwright to run e2e tests for Chrome (desktop) and Safari (mobile)
Resolves: #xxx
> feat: playwright testing

- apps/app/src/routes/(app)/category/[slug]/+page.svelte
> fix: always make network request to get reminders

- .eslintrc.js
- apps/app/codegen.yml
- apps/app/package.json
- apps/app/src/graphql/mutations/addReminder.graphql
- apps/app/src/graphql/queries/getReminders.graphql
- apps/app/src/graphql/types.ts
- apps/app/src/routes/(app)/category/[slug]/+page.svelte
- apps/app/src/routes/(app)/reminder/+layout.svelte
- apps/app/src/routes/(app)/settings/+page.svelte
- pnpm-lock.yaml
Adding types to our graphql queries so that they match our DB schema
Resolves: #xxx
> feat: add graphql codegen

- apps/app/package.json
- apps/app/playwright.config.ts
- apps/app/tests/login.spec.ts
- apps/app/tests/pom/login.ts
- apps/app/tests/pom/register.ts
- apps/app/tests/register.spec.ts
- apps/marketing/package.json
- pnpm-lock.yaml
Adding Playwright in the application with two basic POM files for login and register.
TODO next: Authentication.
> feat: playwright in app

- .github/workflows/testing.yml
- apps/app/package.json
- apps/app/src/routes/(auth)/login/+page.svelte
- apps/app/src/routes/(auth)/register/+page.svelte
- apps/app/tests/login.spec.ts
- apps/app/tests/register.spec.ts
- apps/marketing/package.json
- apps/marketing/src/routes/+page.svelte
- apps/marketing/tests/homepage.spec.ts
- package.json
- pnpm-lock.yaml
- turbo.json
Adding accessibility testing to both applications with tag annotation concept.
Resolves: #xxx
> feat: accessibility testing

- apps/app/src/routes/(app)/reminder/(update)/+layout.svelte
- apps/app/src/routes/(app)/reminder/(update)/add/Submit.svelte
Adding some basic styles and form fields for add reminder
> chore: add reminder styles

- apps/app/src/routes/(auth)/login/+page.svelte
For some reason the styles differ. Needs investigation.
> fix: styles in prod for login

- .github/workflows/testing.yml
> fix: missing pipeline environment variable

- .eslintrc.js
- apps/app/src/components/table/Table.svelte
- apps/app/src/routes/(app)/reminder/[slug]/+page.svelte
- apps/app/src/routes/(auth)/login/+page.svelte
- apps/marketing/src/routes/+page.server.ts
- apps/marketing/src/routes/+page.svelte
- package.json
- pnpm-lock.yaml
> fix: types

- .eslintrc.js
- apps/app/src/routes/(app)/settings/update-password/+page.server.ts
- apps/app/src/routes/(app)/settings/update-password/+page.svelte
- apps/app/src/routes/(auth)/auth/callback/+server.ts
- apps/app/src/routes/(auth)/forgot-password/+page.server.ts
- apps/app/src/routes/(auth)/forgot-password/+page.svelte
- apps/app/src/routes/(auth)/login/+page.svelte
- apps/app/src/routes/(auth)/register/+page.svelte
- apps/app/src/routes/(auth)/styles.css
- components/button/Button.svelte
- components/index.ts
- components/input/Input.svelte
Followed supabase instructions - https://supabase.com/docs/guides/auth/auth-password-reset?language=js#sending-password-reset-email
- Forgot password page
- Update password page
- Created input component
- Share styles between register and login
- Tidy up register page
Resolves: #xxx
> feat: forgot password page

- apps/app/package.json
- apps/app/src/routes/(app)/settings/update-password/+page.svelte
- apps/app/src/routes/(auth)/auth/callback/+server.ts
- apps/app/src/routes/(auth)/forgot-password/+page.server.ts
- apps/app/src/routes/(auth)/register/+page.svelte
- apps/marketing/package.json
Address previous PR comments
Resolves: #xxx
> chore: rename next to goto

- apps/app/tests/login.spec.ts
- apps/app/tests/register.spec.ts
> fix: functional app tests

- apps/app/src/components/navigation/Navigation.svelte
> fix: nav desktop

- .prettierrc.js
- apps/app/src/routes/(app)/+page.svelte
- apps/app/src/routes/(app)/category/[slug]/+page.svelte
- apps/app/static/global.css
> chore: tidy up table styles

- apps/app/src/components/navigation/Navigation.svelte
- apps/app/src/graphql/mutations/addReminder.graphql
- apps/app/src/graphql/mutations/updateSettings.graphql
- apps/app/src/routes/(app)/reminder/(update)/add/+page.server.ts
- apps/app/src/routes/(app)/settings/+page.server.ts
- when in a reminder, make sure nav item for that category is highlighted
- navigation position fixed
- navigation mobile close it when clicking links
- tidy up mutations
Resolves: #xxx
> chore: tidy up navigation styles and tidy up mutations

- apps/app/src/graphql/mutations/updateReminder.graphql
- apps/app/src/routes/(app)/category/[slug]/[slug]/+page.svelte
- apps/app/src/routes/(app)/reminder/+layout.svelte
- apps/app/src/routes/(app)/reminder/add/+page.ts
- apps/app/src/routes/(app)/reminder/edit/[slug]/+page.server.ts
- apps/app/src/routes/(app)/reminder/edit/[slug]/+page.ts
- apps/app/src/routes/(app)/reminder/edit/[slug]/Submit.svelte
- components/link/Link.svelte
> feat: edit reminder functionality

- apps/app/src/graphql/mutations/deleteReminder.graphql
- apps/app/src/routes/(app)/reminder/+layout.svelte
- apps/app/src/routes/(app)/reminder/add/+page.svelte
- apps/app/src/routes/(app)/reminder/add/+page.ts
- apps/app/src/routes/(app)/reminder/add/Submit.svelte
- apps/app/src/routes/(app)/reminder/edit/[slug]/+page.server.ts
- apps/app/src/routes/(app)/reminder/edit/[slug]/+page.svelte
- apps/app/src/routes/(app)/reminder/edit/[slug]/+page.ts
- apps/app/src/routes/(app)/reminder/edit/[slug]/Submit.svelte
- components/link/Link.svelte
> feat: delete reminder

- apps/app/src/graphql/mutations/addReminder.graphql
- apps/app/src/routes/(app)/reminder/+layout.svelte
- apps/app/src/routes/(app)/reminder/add/+page.server.ts
- apps/app/src/routes/(app)/reminder/edit/[slug]/+page.server.ts
> feat: add category input with filtering list as you type
